segtypes/ci8palette.py

hotfix remove PIL import

---

util/Yay0decompress.py

You might like to do a sanity check as I'm using WSL and therefore can't run the 32bit elf to build papermario.. but running `make setup` with a `make clean` in between gives me:
**before**:
```
real    1m8.164s
user    0m58.844s
sys     0m6.250s
```
**after**:
```
real    0m41.790s
user    0m33.000s
sys     0m5.922s
```

pre-allocate decompressed array rather than using append or +=

---

split.py

Allow user to configure symbol_addrs + undefined_syms file paths

---

util/rominfo.py

default 'encoding' to ASCII in rominfo's get_info()

---

segtypes/n64/header.py
split.py

Added DISCARD section to generated linker script, changed rom header to always be in .data to link correctly

---

segtypes/linker_entry.py
split.py

https://github.com/pmret/papermario/pull/262

Make parsed yaml config global & linker_entry fixes

---

segtypes/segment.py

tested against conker, papermario and sssv.

explicitly import importlib.util

---

segtypes/linker_entry.py

I have non-aligned `data/.data/.rodata` which gets compiled with 0x10 alignment. I need some `AT` linker hackery to truncate my oversized objects :)
```yaml
- [0x339C0, .data, data/339C0]
- [0x33A68, .data, data/33A68]  # this
- [0x33B20, .data, data/33B20]
```

Allow ld subalign hack via 'enable_ld_alignment_hack'

---

segtypes/common/c.py
util/options.py

Let me know if you think the option should either:
1. have a different name
2. be in a different place

Add option to prevent rodata being written to generated asm

---

CHANGELOG.md

(Not sure if the changelog should be updated post-release)

Fix option names in changelog

---

segtypes/common/code.py
segtypes/common/group.py
segtypes/linker_entry.py
split.py

Fixed bug pertaining to empty top-level code segments being allowed
Edited some comments
Removed useless(?) field in LinkerWriter
Fixed tqdm descriptions to actually update properly

Assorted fixes

---

segtypes/common/code.py
segtypes/linker_entry.py
segtypes/segment.py

- Adds .bss_contains_common option for segments to make (.bss) sections into (.bss COMMON .scommon)
- Makes this option be inherited by subsegments in code segments.

Add option for common sections for .bss segments.

---

segtypes/common/asm.py
segtypes/common/bin.py
segtypes/common/bss.py
segtypes/common/code.py
segtypes/common/codesubsegment.py
segtypes/common/decompressor.py
segtypes/common/group.py
segtypes/common/hasm.py
segtypes/common/lib.py
segtypes/n64/gfx.py
segtypes/n64/img.py
segtypes/n64/palette.py
segtypes/n64/vtx.py
segtypes/segment.py
split.py
util/log.py

Removes all those said usages in `vram_start`, `rom_start` and `rom_end`.
I kept the `"auto"` check in `parse_segment_start` so yamls having auto should not have any problem updating, I hope :sweat_smile:

Remove all the `"auto"` usages and change them to `None`

---

segtypes/linker_entry.py
segtypes/n64/img.py
segtypes/n64/palette.py
segtypes/segment.py

Allow disabling subalign directive in linker script

---

CHANGELOG.md
disassembler/spimdisasm_disassembler.py
requirements.txt
segtypes/common/codesubsegment.py
split.py

Support for the PSX GTE instructions.

Add support for GTE instructions

---

split.py
util/progress_bar.py
util/relocs.py
util/symbols.py

To avoid passing the flag everywhere I decided to abstract the progress bar to its own file

Option to print all normal output to `stdout`

---

CHANGELOG.md
segtypes/common/c.py
split.py
util/log.py
util/relocs.py
util/symbols.py

* Add a check to prevent relocs with duplicated rom addresses.
* Check empty functions only have 2 instructions before autodecompiling them.

Misc fixes

---

segtypes/common/textbin.py

Also fixes `asm_end_label` being ignored for `textbin`s

Fix `databin` and `rodatabin` not using dlabel

---

docs/Examples.md

This is mainly a dummy commit to trigger the GHA and see if it works as it should

[Wiki] Update list of example projects

---

docs/Configuration.md
docs/General-Workflow.md
docs/Quickstart.md
docs/Segments.md

- Tried to improve General Workflow with a bit more context and bigger examples
- Added a link to General Workflow from Quickstart to improve the reading experience
- Added `data` and `rodata` plus their dot-variants to Segments, to have some info to read back on
I hope you guys appreciate what I wrote. If there are any inconsistencies or things that are untrue, I'd appreciate to let me know, so I could fix them.

My attempt at improving documentation

---

CHANGELOG.md
split.py
test.py
util/symbols.py

Hopefully closes #283 and #282.
I think a symbol should be unique by looking at name, vram and rom. perhaps I dont even need to look at name?

Symbol addrs checks

---

segtypes/linker_entry.py

Sort header_symbols before writing out

---

create_config.py

fix create_config - undefined_funcs_*_path are str not list

---

CHANGELOG.md
requirements.txt
segtypes/common/codesubsegment.py
split.py

Waiting on a release of rabbitizer 1.8.0

Fix r5900 disassembly issues

---

CHANGELOG.md
split.py

Mainly for the undefined auto files

Ensure more directories exist before creating files

---

.github/workflows/black.yml
.github/workflows/mypy.yml
.github/workflows/pypi.yml

bump github action deps

---

src/splat/segtypes/common/rodata.py

Expand 'rodata malignment' check to ps2 platform

---

docs/Examples.md

This PR gives a little bit of company to the Kingdom Hearts decomp on the PS2 project examples. ❤️

Add 'PaRappa the Rapper 2' to the project examples

---

CHANGELOG.md
README.md
pyproject.toml
src/splat/__init__.py
src/splat/segtypes/psx/header.py

Fixup psx header (SPE binaries)

---

CHANGELOG.md
README.md
docs/Configuration.md
docs/General-Workflow.md
docs/Quickstart.md
docs/Segments.md
pyproject.toml
src/splat/__init__.py
src/splat/scripts/create_config.py
src/splat/scripts/split.py
src/splat/segtypes/common/__init__.py
src/splat/segtypes/common/c.py
src/splat/segtypes/common/code.py
src/splat/segtypes/common/linker_offset.py
src/splat/segtypes/n64/__init__.py
src/splat/segtypes/n64/decompressor.py
src/splat/segtypes/n64/img.py
src/splat/segtypes/n64/ipl3.py
src/splat/segtypes/n64/palette.py
src/splat/segtypes/n64/segment.py
src/splat/segtypes/psp/__init__.py
src/splat/segtypes/psp/segment.py
src/splat/segtypes/psx/__init__.py
src/splat/segtypes/psx/segment.py
src/splat/segtypes/segment.py
src/splat/util/options.py

Finally got around to documenting all remaining segment types, cleaning some things up, and hopefully preventing more user error in the future.
@mkst added you as a reviewer since you made the lib segment iirc, and I want to make sure it looks okay.
Resolves #299 , #398

Doc updates & housekeeping

---

CHANGELOG.md
README.md
pyproject.toml
src/splat/__init__.py
src/splat/segtypes/common/bin.py

Error on zero-sized bins
