segtypes/bin.py, segtypes/code.py, segtypes/header.py
Causes ld scripts to link `.s` as `.s.o` rather than just `.o` for example
=> Add o_as_suffix option

segtypes/segment.py, split.py
`ld_addrs.h` can be trivially generated using the below Makefile target, so it's not needed in splat anymore.
```Makefile
include/ld_addrs.h: $(BUILD_DIR)/$(LD_SCRIPT)
grep -E "[^ ]+ =" $< -o | sed 's/^/extern void* /; s/ =/;/' > $@
```
---
This commit also improves ld script output to look like this, which is admittedly harder to read*:
```
/* 0xA4000040 40-1000 (len FC0) */
code_boot_ROM_START = __romPos;
code_boot_VRAM = ADDR(.code_boot);
.code_boot 0xA4000040 : AT(code_boot_ROM_START) {
BUILD_DIR/asm/boot.s.o(.text);
BUILD_DIR/bin/bootcode_font.bin.o(.data);
}
code_boot_ROM_END = __romPos + SIZEOF(.code_boot);
__romPos += SIZEOF(.code_boot);
```
This improves shiftability by not hardcoding ROM_START and ROM_END for each segment - only the VRAM address. This means if a segment changes …
=> Remove ld_addrs.h generation

segtypes/segment.py
This extends #14 by requiring `-DSHIFT` for linker shifting to be enabled. This resolves some problems stuck had with the original implementation, and fixes up some issues with unaligned `bin` segments (e.g. partially-reverse-engineered data segments; which is the reason why https://github.com/ethteck/papermario/pull/111 is failing).
=> Add SHIFT option for ld

segtypes/header.py, util/rominfo.py
This is a fix for issue #46, tried to keep everything as simple as possible, for splits with split.py one can add "header_encoding: ENC_TYPE" to options in the .yaml file, for rominfo.py one can pass --encoding ENC_TYPE, all of these will default to ASCII if no encoding type is provided.
=> Add arguments for non-ASCII encoding in header

segtypes/n64/header.py
Useful for headers with unusual encodings.
=> Ability to output internal name as .word directives.

segtypes/n64/asm.py, segtypes/n64/codesubsegment.py
This is a nice feature that allows for assembled objects to report function size correctly. If the option `asm_endlabels` is set, splat generates an `endlabel [label]` line at the end of every function in asm files.
This can be used in conjunction with macro.inc to add .ent and .end directives to asm files, which in turn ensures that `as` correctly saves the size of functions.
Doing this ensure `objdump -x` will show the correct size for asm functions (as opposed to zero without it) in the final linked elf, which is helpful for making more accurate progress scripts.
=> Added option for endlabel generation on asm files

CHANGELOG.md, segtypes/linker_entry.py, segtypes/n64/ci4.py, segtypes/n64/ci8.py, segtypes/n64/group.py, segtypes/n64/img.py, segtypes/n64/palette.py, segtypes/n64/rgba16.py, segtypes/segment.py, util/iter.py, util/log.py
* Image segment changes:
* Added `flip_x` and `flip_y` boolean parameters to replace `flip`.
* `flip` is deprecated and will produce a warning when used.
* Fixed flipping of `ci4` and `ci8` images.
* Fixed `extract: false` (and `start: auto`) behaviour.
=> N64SegImg fixes

create_config.py, util/n64/rominfo.py
- minor 'bugfix'  putting `basename` inside `options` to prevent basename defaulting to `None`
- adding compiler (based on logic in rom_info)
- adding other `options` (with defaults + commented out) for reference
- switched to `f"{var}"` style as this is already used in rom_info (Python 3.6+)
- couple of formatting tweaks
=> Updating 'options' section for create_config.py

segtypes/linker_entry.py, segtypes/n64/linker_offset.py
`[_, linker_offset, name]` generates a linker symbol `name_OFFSET = . - parent_ROM_START` at its position in the linker script.
For example:
```yaml
- type: group
dir: charset
start: 0x10F1B0
subsegments:
- [0x10F1B0, linker_offset,       standard]
- [0x10F1B0, pm_charset,          standard, 16, 16, 0xA6]
- [0x1144B0, linker_offset,       standard_pal]
- [0x1144B0, pm_charset_palettes, standard,         0x50]
- [0x1149B0, linker_offset,       title]
- [0x1149B0, pm_charset,          title,    12, 15, 0x29]
- [0x115910, linker_offset,       subtitle]
- [0x115910, pm_charset,          subtitle, 12, 12, 0x29]
- [0x116498, linker_offset,       credits_pal]
```
Results in the linker section:
```
charset_ROM_START = __romPos;
charset_VRAM = ADDR(.charset);
.charset : AT(charset_ROM_START) …
```
=> add linker_offset segtype

segtypes/n64/asm.py, segtypes/psx/asm.py, util/options.py
I added the option to append onto the existing assembly preamble. You can see it being used here to suppress compiler warnings about odd-fp regs: https://github.com/Drahsid/turok3/blob/bfc9a8b88f147f5cc1b856a7146c7b611bde30ee/turok3.yaml#L11
=> Add "generated_s_preamble" option

segtypes/common/c.py
I removed redundant behavior, since the gcc case caused the unintended behavior of splitting functions that were matched.
=> do not split redundant matching functions

segtypes/linker_entry.py, util/options.py
Seems to be an bug if there is only one `.bss` segment and its the final segment (which it would be), if there are multiple `.bss` segments the bug doesnt present itself. Hopefully this change doesnt break pmret.
before:
```
overlay2_DATA_END = .;
build/src.us/overlay2_6A6500.c.o(.bss);
overlay2_BSS_START = .;
overlay2_BSS_END = .;
```
after:
```
overlay1_DATA_END = .;
overlay1_BSS_START = .;
build/src.us/overlay1_6384F0.c.o(.bss);
overlay1_BSS_END = .;
```
although I guess it doesnt *actually* harm anything as the start is the same.. just looks wrong
=> simplify BSS_START logic

segtypes/common/codesubsegment.py, util/options.py
This is useful along with the previously added `asm_endlabels` for preventing assembler warnings caused by .ent appearing outside of .text sections, as the .ent directive can just be added to the function label macro instead of glabel itself.
=> Added 'use_function_labels' option, which emits func instead of glabel for functions when enabled

.gitignore, README.md, create_config.py, segtypes/n64/header.py, util/n64/rominfo.py
e.g. before:
```
$ python3 util/n64/rominfo.py 'Bokujou Monogatari 2 (Japan).n64'
splat could not decode the game name; try using a different encoding by passing the --encoding argument (see docs.python.org/3/library/codecs.html#standard-encodings for valid encodings)
```
now:
```
$ python3 util/n64/rominfo.py 'Bokujou Monogatari 2 (Japan).n64'
Warning: Input file has .n64 suffix, byte-swapping!
Writing down Bokujou Monogatari 2 (Japan).z64
Image name: ﾎﾞｸｼﾞｮｳﾓﾉｶﾞﾀﾘ2
Country code: J - Japanese
Libultra version: I
CRC1: B3D451C6
CRC2: E1CB58E2
CIC: 6102 / 7101
RAM entry point: 0x80025c00
Encoding: shift_jis
0 branches and 3 jumps detected in the first code segment. Compiler is most likely GCC
```
NOTE: also handling for .n64 files which will be written down as .z64 assuming a file with …
=> Improvements to rominfo.py

util/color.py, util/symbols.py
the `log` change is to fix:
```
splat 0.8.0.0
Loading and processing symbols
Traceback (most recent call last):
File "tools/splat/split.py", line 314, in <module>
main(args.config, args.basedir, args.target, args.modes, args.verbose, args.use_cache)
File "tools/splat/split.py", line 201, in main
symbols.initialize(all_segments)
File "/sssv/tools/splat/util/symbols.py", line 64, in initialize
Logger.error(f"Invalid value {val} for attribute on line: {line}")
TypeError: error() missing 1 required positional argument: 'msg'
make: *** [Makefile:168: extract] Error 1
```
the `continue` change is to fix:
```
splat 0.8.0.0
Loading and processing symbols
Invalid value 0x6ABC64 for attribute on line: set_fog_factor_and_color   = 0x8029A5B4;
make: *** [Makefile:168: extract] Error 2
```
the …
=> Fixing a few bugs

segtypes/common/codesubsegment.py
without this change:
```# python3 tools/splat/split.py bootloader.yaml
splat 0.8.0.0
Loading and processing symbols
Starting scan
..Traceback (most recent call last):
File "tools/splat/split.py", line 314, in <module>
main(args.config, args.basedir, args.target, args.modes, args.verbose, args.use_cache)
File "tools/splat/split.py", line 232, in main
segment.scan(rom_bytes)
File "/ctr/tools/splat/segtypes/common/group.py", line 214, in scan
sub.scan(rom_bytes)
File "/ctr/tools/splat/segtypes/common/asm.py", line 14, in scan
self.funcs_text = self.scan_code(rom_bytes, is_asm=True)
File "/ctr/tools/splat/segtypes/common/codesubsegment.py", line 103, in scan_code
self.determine_symbols()
File "/ctr/tools/splat/segtypes/common/codesubsegment.py", line 285, in determine_symbols
gp_offset = …
```
=> Allow for $(gp) with no offset

segtypes/common/c.py, segtypes/common/data.py, split.py, util/n64/find_code_length.py, util/n64/rominfo.py, util/options.py
Add `data_path` and `nonmatchings_path` options to specify directories to put these two in, rather than hardcoding them in the functions. Defaults to current behaviour if not specified.
Also fixed a bug where the dir was printed twice in the `GLOBAL_ASM` statement in the C files, and made all the #!s `/usr/bin/env python3` since apparently this is the more correct way.
=> Options for changing data and nonmatchings' directiories

util/options.py
the issue would only surface if `base_path` was not `.`, but best to not break if someone wants to configure their base path.
=> Fix data_path + nonmatching_path fallbacks, add some more type hints

util/symbols.py
=> Fix extra colon in symbols.py:

segtypes/common/c.py
This fixes the paths to point to the correct relative directory, at least for MP1. In theory this has been broken for any other game that uses `dir` and the legacy `INCLUDE_ASM` style.
=> Correct GCC/SN `INCLUDE_ASM` path generation

create_config.py, util/n64/find_code_length.py, util/n64/rominfo.py
Non-important changes to make the code look/behave better
- Generic Python cleanup
- String formatting changes
- More type annotations
- Check if rom file exists in `create_config`
- Change crc1/crc2 to "checksum" (see "Checksum" on https://n64brew.dev/wiki/ROM_Header , specifically *"Sometimes, these 8 bytes are referred to as "CRC HI" / "CRC LO" or "CRC1/2", but the checksum algorithm is not a CRC, and splitting into two 4-byte words seem confusing when it is really a 64-bit value."*)
- Remove a `# TODO: support .n64 extension` as I think that's handled (in `rominfo.read_rom`)
=> Cleanup/fixup/refactor create_config related code

segtypes/common/data.py
This fixes a very specific case where splat misinterpreted an array of functions with a jump table. This situation could only happen if said array only contained multiple references to the same exact function.
Example from [Yoshi's Story repo](https://github.com/decompals/yoshis-story/):
```mips
glabel jtbl_800A6570
.word L80062D50_63950, L80062D50_63950, L80062D50_63950, L80062D50_63950, L80062D50_63950, 0, 0, 0
```
This could build without issue because splat was generating this extra label on the corresponding function:
```mips
glabel func_80062D50
glabel L80062D50_63950
/* 63950 80062D50 27BDFFE0 */  addiu      $sp, $sp, -0x20
```
With this fix:
```mips
glabel D_800A6570
.word func_80062D50, func_80062D50, func_80062D50, func_80062D50, func_80062D50, 0x00000000, 0x00000000, 0x00000000 …
```
=> Don't mark symbols as jtbls if any of its labels point to the start of its corresponding function

segtypes/n64/ia16.py
this change is to fix:
```Traceback (most recent call last):
File "/home/user/repo/papermario/tools/build/configure.py", line 788, in <module>
configure.split(not args.no_split_assets, args.split_code, args.debug)
File "/home/user/repo/papermario/tools/build/configure.py", line 244, in split
split.main(
File "/home/user/repo/papermario/tools/splat/split.py", line 373, in main
segment.split(rom_bytes)
File "/home/user/repo/papermario/tools/splat/segtypes/common/group.py", line 112, in split
sub.split(rom_bytes)
File "/home/user/repo/papermario/tools/splat/segtypes/common/data.py", line 33, in split
CommonSegGroup.split(self, rom_bytes)
File "/home/user/repo/papermario/tools/splat/segtypes/common/group.py", line 112, in split
sub.split(rom_bytes)
File …
```
=> ia16 segment bugfix

segtypes/linker_entry.py
This can be useful to reference the size of a segment in a C/Assembly file.
The generated symbol will look like this in the linker script
```
boot_BSS_SIZE = ABSOLUTE(boot_BSS_END - boot_BSS_START);
```
And like this in the map file
```
0x0000000000018de0                boot_BSS_SIZE = ABSOLUTE ((boot_BSS_END - boot_BSS_START))
```
=> Output a `_SIZE` symbol for each segment in the linker script

segtypes/common/c.py, segtypes/n64/asm.py, segtypes/n64/hasm.py, util/floats.py, util/options.py
Allows to splat generate `.asmproc.d` files, which adds Makefile dependencies for the C files on the corresponding assembly function files.
For example, if file `src/boot/2F80.c` still has `INCLUDE_ASM` for `func_800023B4` and `func_80002400`, then the `build/src/boot/2F80.d` file will be generated and will look like this:
```makefile
build/src/boot/2F80.o: \
asm/nonmatchings/boot/2F80/func_800023B4.s \
asm/nonmatchings/boot/2F80/func_80002400.s
```
This allows to add the following on the main Makefile, which will trigger the rebuilding of the corresponding C file if the assembly function is touched:
```makefile
DEP_FILES := $(O_FILES:.o=.asmproc.d)
-include $(DEP_FILES)
```
This setting is enabled by default, should be instead be off by default?
This setting can be enabled/disabled by …
=> Generate dependency files for C files

create_config.py, platforms/n64.py, split.py, util/options.py, util/symbols.py
`spimdisasm` has those symbols by baked into it, so why not?
This option is turned off by default because the user will need to add those symbols to a linker script manually.
I also added a check for the minimal `spimdisasm` version which splat requires
=> Add option to automatically add libultra symbols and named hardware registers

segtypes/common/sbss.py, segtypes/common/sdata.py, segtypes/psx/asm.py
Creating a PR for comments. `.sbss` shouldnt be included in the output (they should be DISCARD'd), however ESA devs were dumb and they include both `.sbss` and `.bss` in the binary (wasted space of pure zeroes) - so this change works for me, but would likely need extending for anyone with a psx decomp with better developers :)
=> Remove comments for psx assembly preamble

util/options.py
If you add an unknown key you now get an error like
```
$ ./tools/splat/split.py ver/us/splat.yaml 
splat 0.12.4 (powered by spimdisasm 1.7.5)
Traceback (most recent call last):
File "/home/simon/code/decomp/papermario/./tools/splat/split.py", line 508, in <module>
main(args.config, args.modes, args.verbose, args.use_cache)
File "/home/simon/code/decomp/papermario/./tools/splat/split.py", line 278, in main
options.initialize(config, config_path, modes, verbose)
File "/home/simon/code/decomp/papermario/tools/splat/util/options.py", line 383, in initialize
opts = _parse_yaml(
File "/home/simon/code/decomp/papermario/tools/splat/util/options.py", line 368, in _parse_yaml
p.check_no_unread_opts()
File "/home/simon/code/decomp/papermario/tools/splat/util/options.py", line 232, in …
```
=> Check for unrecognized yaml config keys

CHANGELOG.md, requirements.txt, split.py, util/symbols.py
A change introduced in spimdisasm version 1.7.0 prevented its data analyzer to see symbols which were only referenced by data symbols because the allowed vram ranges were changed to not be hardcodded, meaning it must be configured during setup. This PR addresses this problem. Addressing this implies bumping the minimal required spimdisasm version to 1.7.1
I also added a check to prevent segments tagged with `exclusive_ram_id` to have an overlapping VRAM range with non `exclusive_ram_id` segments. I didn't know if this should be an error and halt the execution or just warn to the user and let them do whatever they want, but I ended up opting for warning the user and letting them go ahead
=> Fix spimdisasm not seeing some symbols on its latest version

CHANGELOG.md, segtypes/common/code.py, segtypes/common/codesubsegment.py, segtypes/common/group.py, segtypes/n64/ipl3.py, segtypes/n64/rsp.py, segtypes/segment.py, split.py, util/options.py, util/symbols.py
Adds two new N64-specific segments:
- IPL3: Allows setting its correct VRAM address without messing the global segment detection (as suggested by wiseguy)
- RSP: Allows disassembling using the RSP instruction set instead of the default one
Also the PS2 platform was added with very basic support: Setting PS2 as platform in the yaml file will allow using the R5900's instruction set. 
I decided to just add this so people can start messing with PS2 disassemblies
=> IPL3 and RSP segments & PS2 platform

segtypes/common/rodata.py
Some rodata symbols can't be migrated to a function because they may be used by multiple functions so each one of them is exported to its own file which can be included with `INCLUDE_ASM`/`GLOBAL_ASM`.
This behavior only makes sense when doing the `rodata` -> `.rodata` thingy but the file has symbols which can't be migrated, but currently those files are being exported even when not trying to migrate the rodata yet, so it plagues the asm folder with a ton of files. This is addressed by this PR by only doing this when `partial_migration` is `True`
Also, I changed the path of where they are written to so they are put in the same folder where the functions are put (the non_matching folder)
=> Avoid creating unnecesary rodata files for each symbol

CHANGELOG.md, requirements.txt, segtypes/common/c.py, segtypes/common/codesubsegment.py, segtypes/common/rodata.py, split.py, util/compiler.py, util/options.py, util/symbols.py
- Allow setting a different macro for jumptable labels with `asm_jtbl_label_macro`
- The currently recommended one is `jlabel` instead of `glabel`
- Two new options for symbols: `force_migration` and `force_not_migration`
- Useful for weird cases where the disassembler decided a rodata symbol must (or must not) be migrated when it really shouldn't (or should)
- Fix `str_encoding` defaulting to `False` instead of `None`
- Output empty rules in generated dependency files to avoid issues when the function file does not exist anymore (i.e. when it gets matched)
- Allow changing the `include_macro_inc` option in the yaml
=> Change the jumptable macro, force (not) migration and other misc stuff

util/symbols.py
For some reason using `LXXXXXXXX` labels for jumptable labels messes with asm differ, preventing using it at any function with jumptables, at least on gcc kmc. Using `.LXXXXXXXX` (with a dot prefix) seems to fix this issue.
As a reference, this is the traceback of asm differ:
```
Traceback (most recent call last):
File "/home/angie/Documents/n64decomp/drmario64/./diff.py", line 3359, in <module>
main()
File "/home/angie/Documents/n64decomp/drmario64/./diff.py", line 3304, in main
display = Display(basedump, mydump, config)
File "/home/angie/Documents/n64decomp/drmario64/./diff.py", line 3130, in __init__
self.base_lines = process(basedump, config)
File "/home/angie/Documents/n64decomp/drmario64/./diff.py", line 2255, in process
original, reloc_symbol = processor.process_reloc(reloc_row, …
```
=> Use `.L` as prefix for jtbl labels

requirements.txt, segtypes/n64/i1.py, segtypes/n64/ia1.py
This PR pending changes to n64img.
I believe the definition for ia4 in n64img needs to be duplicated and renamed to ia1. Then change the final arithmetic from `// 2` to `// 8`
There may also be a bug with n64img not supporting 13x14 textures (which is the boot font)
This would be a nice have for mk64 as it uses this file type for the crash screen font.
=> Add i1 support

CHANGELOG.md, requirements.txt, split.py, util/options.py, util/relocs.py, util/symbols.py
Adds the ability to provide user-defined relocs to the disassembler. This can be useful to improve automatic disassembly, use negative addends which aren't used by default by the disassembler or use different symbols which happen to have the same vram.
The user can pass those relocs using the `reloc_addrs.txt` file. This file has the following format:
```
rom:ROMADDR symbol:SYMBOLNAME reloc:RELOCTYPE
```
Where
- `ROMADDR` is the rom address of the instruction which the user want to change, it must be either decimal or hex with a leading 0x.
- `SYMBOLNAME` is the symbol to use.
- `RELOCTYPE` is the relocation type to use. It must be a valid relocation type. The most common ones are `MIPS_HI16`, `MIPS_LO16` and `MIPS_26`. A list can be seen …
=> User-defined relocations

CHANGELOG.md, segtypes/common/c.py, split.py
Try to detect and warn to the user if a gap between two migrated rodata symbols is detected and suggest possible solutions to the user.
A gap in migrated rodata symbols is a situation when some symbols are migrated to a function but some symbols in the middle of said symbols are not migrated for whatever reason.
Example of the warning:
```
A gap was detected in migrated rodata symbols!
In function 'menuMain_input' (0x8004F358), gap detected between '_mesNoCont2' (0x800AF3C4) and 'jtbl_800B0450' (0x800B0450)
The address of the missing rodata symbol is 0x800AF3F8
Try to force the migration of that symbol with `force_migration:True` in the symbol_addrs.txt file; or avoid the migration of symbols around this address with `force:not_migration:True`
```
=> Warn if migrated rodata symbols have gaps

CHANGELOG.md, segtypes/common/bss.py, segtypes/common/c.py, segtypes/common/code.py, segtypes/common/codesubsegment.py, segtypes/common/data.py, segtypes/common/group.py, segtypes/segment.py, split.py
Allow omitting the rom offset (`start:` in the yaml) for bss segments.
Example of current behavior:
```yaml
- { start: 0x09B460, type: bss, vram: 0x800B3640, name: main_segment/800B3640 }
- { start: 0x09B460, type: bss, vram: 0x800E99C0, name: libmus/aud_sched }
- { start: 0x09B460, type: bss, vram: 0x800E99D0, name: main_segment/800E99D0 }
- { start: 0x09B460, type: bss, vram: 0x800E9BA0, name: libmus/aud_samples }
- { start: 0x09B460, type: bss, vram: 0x800E9BB0, name: main_segment/800E9BB0 }
- { start: 0x09B460, type: bss, vram: 0x800F8C90, name: libmus/aud_thread }
- { start: 0x09B460, type: bss, vram: 0x800F8CE0, name: main_segment/800F8CE0 }
```
New:
```yaml
- { type: bss, vram: 0x800B3640, name: main_segment/800B3640 }
- { type: bss, vram: 0x800E99C0, name: libmus/aud_sched }
- { …
```
=> Allow omitting the rom offset in bss segments

CHANGELOG.md, segtypes/common/asm.py, segtypes/common/c.py, segtypes/common/group.py, segtypes/common/rodata.py, segtypes/segment.py, split.py, util/options.py
- Adds a new option: `find_rodata_to_text` (open to better name suggestions).
- If enabled, splat will try to find to which text segment an unpaired rodata segment belongs and it will hint it to the user.
Example output:
```
Rodata segment 'boot/0012240' may belong to the text segment 'libultra/sched'
Based on the usage from the function __scSchedule to the symbol jtbl_80011640
Rodata segment 'boot/0012260' may belong to the text segment 'libultra/os/exceptasm'
Based on the usage from the function __osException to the symbol jtbl_80011680
Rodata segment 'boot/00122B0' may belong to the text segment 'libultra/devmgr'
Based on the usage from the function __osDevMgrMain to the symbol jtbl_80011730
Rodata segment 'boot/00122B0' may belong to the text segment 'libultra/drvrNew'
Based on the …
```
=> Hint to which segment a rodata segment belongs

create_config.py, util/n64/rominfo.py
The script now parses the entrypoint and tries to extract `bss` information and use it to create the initial yaml.
Now the script is able to now where the `data` section more or less starts too
Example yaml generated with current master:
```yaml
name: Dr.Mario 64 (North America)
sha1: a130d3622ce40e0158db2da4247101f6e92206fc
options:
basename: dr.mario64
target_path: baserom.us.z64
base_path: .
compiler: GCC
find_file_boundaries: True
header_encoding: ASCII
platform: n64
segments:
- name: header
type: header
start: 0x0
- name: boot
type: bin
start: 0x40
- name: main
type: code
start: 0x1000
vram: 0x80000400
subsegments:
- [0x1000, asm]
- type: bin
start: 0xED90
- [0x400000]
```
yaml outputted with this PR:
```yaml
name: Dr.Mario 64 (North America)
sha1: …
```
=> Add bss info to `create_config.py`

CHANGELOG.md, requirements.txt, split.py, util/symbols.py
* An error will be produced if a symbol is declared with an unknown type in the symbol_addrs file.
* The current list of known symbols is `'func', 'label', 'jtbl', 'jtbl_label', 's8', 'u8', 's16', 'u16', 's32', 'u32', 's64', 'u64', 'f32', 'f64', 'Vec3f', 'asciz', 'char*', 'char'`.
* Custom types are allowed if they start with a capital letter.
=> Error on unknown types

util/n64/rominfo.py
When the ROM name in the header is null, create_config crashes because it tries to write a null to the yaml. This PR removes potential nulls at the end of the name and if the entire name is empty, replaces it with "empty". Also it doesn't trim whitespace from the left side of the name any more. Also I fixed some typos in the country codes, hope that doesn't break anything
=> Fix bug with null ROM name

CHANGELOG.md, segtypes/linker_entry.py, split.py, util/options.py
* New option `segment_end_before_align`.
* If enabled, the end symbol for each segment will be placed before the alignment directive for the segment
=> `segment_end_before_align`

test.py
This PR depends on the other one, I will rebase when it is merged. The relevant new changes are in https://github.com/ethteck/splat/commit/6c41021b2e21fa926fa8bd9ad798f405f8473d77
The purpose of this PR is to add some unit tests to usages of spimdisasm in segment.py. My plan is to wrap spimdisasm in a generic interface that disassemblers can implement, so this will help verify that spimdisasm doesn't break.
=>  Add some unit tests for segment.py

test.py, util/symbols.py
This changes the rodata text test so that it has a valid result to check, and adds a test for the disassemble method. Mypy complains about `common_seg_rodata.parent` being set to a `CommonSegGroup`, so I left it as `CommonSegCode`.
=> Improve rodata text test, add disassemble test

CHANGELOG.md, segtypes/segment.py, split.py
discussed and implemented in vc, adds `linker_entry` option to subsegments, which allows you to optionally disable the emission of a linker entry for said subsegment.
=> has linker entry

segtypes/n64/gfx.py
Usually `Vp`s are single variables and not arrays, so we need to pass the address of the variable instead of simply passing the variable
=> Add missing `&` in `vp_handler`

disassembler_section.py, segtypes/common/bss.py, segtypes/common/c.py, segtypes/common/codesubsegment.py, segtypes/common/data.py, segtypes/common/rodata.py, test.py
This PR introduces `DisassemblerSection` to wrap `spimdisasm.mips.sections.SectionBase` and child classes. Usages of it are partially refactored. `get_section()` is used to get the underlying object to avoid doing the refactor all at once.
=> Introduce DisassemblerSection and partial refactor

segtypes/common/code.py
works gud on my local ESA/PSX decomp, also :ok: on sotn decomp (with https://github.com/Xeeynamo/sotn-decomp/pull/247 applied).
=> Fix rodata migration when .rodata sections occur before .text

test.py, util/symbols.py
This adds tests for the symbol attributes functionality and `initialize_spim_context`. I moved some of the code from initialize to `handle_sym_addrs` since it was previously relying on reading from the file system, which makes it harder to test. The diff looks messy but it should just be a copy-paste. Unless I'm misreading the code it seems like this block will never execute since the `global_` values and `overlay_segments` can't be filled out at the same time. https://github.com/ethteck/splat/blob/0363e893123a75579928c94fff5c63e4655ef89d/util/symbols.py#L342
=> Add more tests for symbols.py

CHANGELOG.md, split.py, util/compiler.py, util/options.py
Seems like asm-processor doesn't like the `.size` directive, so it seems better to disable that directive for those projects
=> Turn of the `.size` directive emitted by spimdisasm for IDO projects

CHANGELOG.md, split.py, util/symbols.py
If a symbol declared on the `symbol_addrs.txt` specifies its rom address but not a segment then try to find the corresponding segment for said symbol.
This is useful for projects with overlays that has overlapping vram addresses.
=> Assign segment to user-declared symbol if rom address was provided

CHANGELOG.md, disassembler/spimdisasm_disassembler.py, requirements.txt, segtypes/common/codesubsegment.py, split.py, util/compiler.py, util/options.py
* Add option `detect_redundant_function_end`. It tries to detect redundant and unreferenced functions ends and merge them together.
* This option is ignored if the compiler is not set to IDO.
* This type of codegen is only affected by flags `-g`, `-g1` and `-g2`.
* This option can also be overriden per file.
* Disable `include_macro_inc` by default for IDO projects.
* Disable `asm_emit_size_directive` by default for SN64 projects.
* `spimdisasm` 1.16.0 or above is now required.
=> Redundant function end detection and some other default changes

.github/workflows/black.yml, .github/workflows/unit_tests.yml, CHANGELOG.md, segtypes/common/c.py, segtypes/common/data.py, split.py, util/options.py
Add option `disassemble_all`. If enabled then already matched functions and migrated data will be disassembled to files anyways.
This option can be useful to inspect the assembly of already matched stuff.
=> Option to still disassemble matched functions and migrated data

CHANGELOG.md, segtypes/common/data.py, segtypes/segment.py, split.py
I added this because I stumbled with the fact custom sections don't get linked properly if they don't have the proper flags.
Really there's no real need to have this on splat's side, but I think it would be cleaner to use let splat extensions to use this method instead of requiring them to duplicate the code of the `split` method with a small modification.
GAS docs for the section directive: https://sourceware.org/binutils/docs/as/Section.html#ELF-Version
=> Add `get_section_flags` method to `Segment`

CHANGELOG.md, segtypes/linker_entry.py, split.py, util/options.py
The new option `segment_symbols_style` can be set to generate makerom compatible segment symbols instead of the current style used by splat for segment symbols.
=> Option to generate makerom-compatible segment symbols in the linker script

CHANGELOG.md, segtypes/common/code.py, split.py
The `align` set in a yaml for `code` segments was being ignored and being set unconditionally to `0x10
=> Fix align in code segments

CHANGELOG.md, split.py, util/options.py
Adds disassemble-all as a command line argument for easier use in Makefiles. This keeps the yaml option as well, though does give precedence to the command line arg so will still disassemble everything even if the option is set to false in the yaml.
=> disassemble-all command line argument

segtypes/common/c.py, segtypes/common/cpp.py
Seems to work in a very simple test:
```yaml
- [0x11644, cpp, controller2]
```
gave me:
```
Wrote controller2 to src/esa/controller2.cpp
```
Closes #269.
=> Add 'cpp' segment

create_config.py, util/psx/psxexeinfo.py
`create_config.py` can now create a yaml for PSX-EXE files.
I'm not sure how useful this could be since most files on a psx disk are not exe, but there should always be an exe there, so people could use it as a starting point (?)
Since I'm touching this script I decided to also update the default options for n64 yamls. A few notable changes would be using dlabel, jlabel and o32 register names by default.
=> Implement PSX-EXE parsing in `create_config.py`

disassembler/spimdisasm_disassembler.py, platforms/n64.py, requirements.txt, util/compiler.py, util/options.py
Latest spimdisasm allows to set a different label for symbols in the middle of functions, allowing `glabel` to be used as a proper function entry point.
spimdisasm also has the option to automatically set and name iQue libultra symbols. In earlier versions those symbols were used automatically when using normal libultra symbols, but this new option gives finer control so normal games don't have to worry about this
=> Label for alt symbols and option to automatically fill iQue libultra syms

segtypes/common/bin.py, segtypes/common/code.py, segtypes/common/data.py, segtypes/common/databin.py, segtypes/common/header.py, segtypes/common/rodatabin.py, segtypes/common/textbin.py, segtypes/segment.py
Introduces 3 new segments types, `textbin`, `databin` and `rodatabin` which allows to specify bins in text, data or rodata sections instead of the default.
This generates an asm file that `.incbin`s the outputted bin, specifying the section type, a symbol if the vram address of the file matches a known symbol.
If there is a `databin` and/or `rodatabin` section with the same name as the `textbin` then the generated asm file will also `.incbin` the other segment's bins
=> incbin segments

platforms/n64.py, segtypes/common/textbin.py
- incbin sections was not marking the outputted symbol as defined
- iQue symbols were not being properly filled because the function was not being called :facepalm:
=> Minor fixes

CHANGELOG.md, segtypes/linker_entry.py, split.py, util/options.py
2 new options to fine-tune the linker script generation. Both are a whitelist and a blacklist of sections to discard during linktime.
This can be useful to preserve debugging symbols on the final elf
=> `ld_sections_allowlist` and `ld_sections_denylist` options

.github/workflows/publish_docs_to_wiki.yml, docs/Adding-Symbols.md, docs/Advanced.md, docs/Configuration.md, docs/Examples.md, docs/General-Workflow.md, docs/Home.md, docs/Quickstart.md, docs/Segments.md
Moves the wiki to a docs folder and publishes it automatically to the actual wiki using a Github Action.
I followed the tutorial from https://nimblehq.co/blog/create-github-wiki-pull-request
Please note this PR should **not** be merged until the repo has a secret named `WIKI_ACTION_TOKEN`, containing a PAT with repo access.
I didn't test if the script actually works due to the nature of the PR itself. Expect it to not work first time
=> Move wiki to `docs` folder

docs/Configuration.md, segtypes/common/codesubsegment.py, segtypes/segment.py
Hi,
Today I wanted to be able to specify `find_file_boundaries` on a per segment basis. The use case for this is so that I can disable the setting on segments that I know are complete, while still retaining the helpful messages it generates for segments that I'm not sure are complete.
=> Added the ability to specify `find_file_boundaries` on a per segment basis

CHANGELOG.md, segtypes/common/c.py, segtypes/common/code.py, segtypes/common/cpp.py, split.py
Related: #290 
The issue was caused because splat had a list of text segments that should be analyzed before everything else, but the `cpp` segment was not present on that list, so changing from one segment type to the other changed the behavior of the address symbolizer.
I fixed it by not using a hardcoded list.
I also did a few other cleanups on `segtypes/common/c.py` when trying to figure out the problem
=> Fix rodata errors when using a `cpp` segment

CHANGELOG.md, disassembler/spimdisasm_disassembler.py, requirements.txt, segtypes/common/c.py, split.py
Migrating `.rdata` (not `.rodata`) was broken due to `spimdisasm` hardcoding the section of the migrated symbols instead of allowing to customize it
=> Fix migrated rdata

CHANGELOG.md, docs/Configuration.md, docs/Segments.md, segtypes/linker_entry.py, segtypes/segment.py, split.py, test/basic_app/expected/basic_app.ld, util/options.py
Due to Wiseguy and my investigation on trying to use `lld` (clang's linker) on decomp projects, we discovered `lld` pads executable sections with trap instructions instead of zeroes. The simplest way we found to avoid this behavior was to put a `FILL` statement on each segment on the linker script to force linkers to fill pads with zeroes.
So I went ahead and implemented `FILL` on splat. splat will start emitting `FILL(0)` statements on every segment on the linker script by default. To make it a bit more flexible I also implemented options to choose which value the linker will use as the filler, disable the `FILL`s completely and change the behavior for specific segments.
=> ld_fill_value

CHANGELOG.md, docs/Configuration.md, segtypes/common/bss.py, split.py, util/options.py
Allows to control if `bss` sections (and derivatived sections) will be put on a `NOLOAD` segment on the generated linker script or not.
Applies to all `bss` (`sbss`, `common`, `scommon`, etc) sections.
Defaults to `True`, meaning `bss` sections will be put on `NOLOAD` segments.
=> `ld_bss_is_noload`

CHANGELOG.md, docs/Configuration.md, segtypes/linker_entry.py, split.py, test/basic_app/expected/basic_app.ld, util/options.py
Like #307 but for aligning each individual section
=> `ld_align_section_vram_end`

segtypes/n64/palette.py
A simple bugfix that makes the use of `path.parent.mkdir` like in the other segments.
=> Ensure the directory exists when extracting a palette segment

create_config.py, util/psx/psxexeinfo.py
Closes #315.
Example diff (looking at legacy of kain, which prompted this issue/pr):
```diff
--- slus_007.08.yaml	2023-12-15 14:18:52.115094730 +0000
+++ slus_007.08.yaml.mkst	2023-12-15 14:18:45.739151392 +0000
@@ -15,7 +15,7 @@
ld_script_path: slus_007.08.ld
find_file_boundaries: False
-  gp_value: 0x00000000
+  gp_value: 0x800D5CF8
o_as_suffix: True
use_legacy_include_asm: False
@@ -55,5 +55,6 @@
bss_size: 0x0
subsegments:
- [0x800, rodata, 800]
-      - [0xA7698, asm, A7698]
+      - [0x3550, asm, 3550] # estimated
+      - [0xB8FD4, data, B8FD4] # estimated
- [0xC0800]
```
=> Improve create_config.py for PSX

CHANGELOG.md, docs/Configuration.md, docs/Segments.md, segtypes/common/lib.py, segtypes/common/pad.py, segtypes/linker_entry.py, segtypes/n64/linker_offset.py, split.py, util/options.py
- Add a pad segment that advances the linker script instead of dumping a binary / generating an assembly file.
- Closes #312 
- Move the logic of writing the entry to the linker script from `LinkerWriter` to `LinkerEntry`
- This allows to have custom behavior for an entry without needing to hardcode extra checks on `LinkerWriter`.
- Extension segments can make a subclass of `LinkerEntry` and override its methods to have custom linker script behavior.
- New yaml option: `ld_generate_symbol_per_data_segment`
- If enabled, the generated linker script will have a linker symbol for each data file.
- Defaults to `True`.
=> Add a Pad segment and make LinkerEntry a bit more flexible

CHANGELOG.md, README.md, docs/Configuration.md, pyproject.toml, src/splat/__init__.py, src/splat/segtypes/common/code.py, src/splat/segtypes/segment.py, src/splat/util/options.py
Also added a global option `ld_bss_contains_common`, because setting `bss_contains_common: True` on every segment is kinda annoying
=> Fix `bss_contains_common` not being passed to auto all segments

CHANGELOG.md, README.md, docs/Adding-Symbols.md, pyproject.toml, src/splat/segtypes/common/code.py, src/splat/util/options.py, src/splat/util/symbols.py
Allows to specify specific symbols to not be checked if they have a duplicated name or vram address on the symbol_addrs file.
This way people can use duplicated names without turning off the whole duplicated checker.
This is required by af, which uses original symbols, and there are a few static ones that are duplicated, but we need splat to know their names for asset extraction.
=> `allow_duplicated` attribute for symbols

CHANGELOG.md, README.md, docs/Configuration.md, docs/Segments.md, pyproject.toml, src/splat/__init__.py, src/splat/segtypes/segment.py, src/splat/util/options.py
Per segment `subalign` already accepts `null`, so it makes sense for this one to accept it too
=> Allow the global `subalign` option to accept `null`

CHANGELOG.md, README.md, pyproject.toml, src/splat/__init__.py, src/splat/scripts/create_config.py
Output an error if the file passed to `create_config` is not recognized.
Currently the script prints thing at all, which is confusing for the user.
Inspired by #341
=> `create_config`: Error on unrecognized input

CHANGELOG.md, src/splat/segtypes/common/lib.py
This allows the lib segment to be used as a dictionary.
The following options are allowed:
* object: The name of the object file to link from the archive
* section: The section of the object file to link from the archive
* vram: Allows to specify the vram (important for linking bss from an archive)
Note: I'm wondering if instead of allowing to specify the section we should instead have different segments all together like `bin`? (e.g. `textlib`, `datalib`, `rodatalib`, `bsslib`)
Note 2: I uped the version number and added to changelog, but this no means needs a release yet. We could add to it further. Not sure if you would prefer this PR to some kind of dev branch instead?
=> Allow lib segment to use dict

CHANGELOG.md, src/splat/segtypes/common/rodata.py
Due to GCC for PSX always aligning jumptables to 8 but not aligning the sections themselves then some jumptables may end up not aligned to 8, which we can use as a way to find rodata file splits
=> Add rodata file splits suggestions specific to PSX

src/splat/scripts/create_config.py, src/splat/util/options.py
also align the allowed values with the [same values](https://github.com/Decompollaborate/spimdisasm/blob/0ef84068be2e75b5fd2241a79ac7b837d9f4ac3c/spimdisasm/mips/InstructionConfig.py#L22) as spimdisasm.
=> Don't set mips_abi_float_regs in create_config script

docs/General-Workflow.md, docs/Quickstart.md, src/splat/scripts/create_config.py, src/splat/segtypes/common/data.py
Adds `mips_abi_float_regs` back to `create_config` and add some explanation about it in `General-Workflow.md` and how to setup the `macro.inc` file expected by splat.
I also updated the `Quickstart.md` example with the new output
=> Add `mips_abi_float_regs` option back to `create_config` and add some docs

CHANGELOG.md, README.md, pyproject.toml, src/splat/__init__.py, src/splat/segtypes/linker_entry.py
We noted this problem in parappa 2
=> Fix linker script generation not respecting other noload segments (like `.sbss`) when using `bss_contains_common`

CHANGELOG.md, README.md, pyproject.toml, src/splat/__init__.py, src/splat/segtypes/common/bss.py, src/splat/segtypes/common/sbss.py, src/splat/util/options.py
Now both `bss` and `sbss` behave as noload by default.
To make those sections to not behave as noload then turn off `ld_bss_is_noload`.
Also, since psx projects seem to usually use `ld_bss_is_noload` turned off by default then I made it to be turned of for psx projects.
I tested it on a ps2 project and it works as expected, but I haven't tested it on a psx project yet
=> Change `sbss` to properly behave as noload

CHANGELOG.md, docs/Adding-Symbols.md, src/splat/segtypes/common/c.py, src/splat/util/symbols.py
A way to handle mangled symbols names that may be invalid as filepaths.
I tried to make the error message to explain the issue as much as possible.
It looks like this
```
Loading symbols (elf_symbol_addrs):   0%|                                        | 0/12114 [00:00<?, ?it/s]
error reading config/us/elf_symbol_addrs.txt, line 119:
__opPCc__Q23std34_RefCountedPtr<c,Q23std9_Array<c>>CFv = 0x00202850; // size:0x1C type:func bind = <processor specific> 13
Ilegal symbol filename detected!
The symbol
__opPCc__Q23std34_RefCountedPtr<c,Q23std9_Array<c>>CFv
exceeds the 255 bytes filename limit that most OS imposes or uses illegal characters,
which will be a problem when writing the symbol to its own file.
To fix this specify a `filename` for this symbol, like `filename:func_00202850`.
Make sure …
```
=> `filename` attribute for symbols

src/splat/disassembler/spimdisasm_disassembler.py, src/splat/platforms/ps2.py
Set spimdisasm's ABI config to EABI64 when the platform is ps2.
This can help a little bit since spimdisasm has some checks in place for the o32 ABI (the default) that are bad for ps2 games (like double float detection on odd float registers).
Also moved the ps2 settings from `spimdisasm_disassembler.py` to `platforms/ps2.py`
=> Set ABI for ps2

CHANGELOG.md, docs/Configuration.md, src/splat/segtypes/linker_entry.py, src/splat/util/options.py
`ld_section_labels` was redundant so lets just remove it.
I also added an error message to the linker script generator in case a section is missing from the `section_order`. It looks like this
```
Linker script main:   0%|                                                  | 0/5 [00:00<?, ?it/s]
Error on linker script generation: section '.vutext' not found.
Make sure the section '.vutext' is listed on 'section_order' of the yaml options.
```
=> Remove `ld_section_labels`

CHANGELOG.md, docs/Segments.md, pyproject.toml, requirements.txt, src/splat/disassembler/spimdisasm_disassembler.py, src/splat/segtypes/common/bss.py, src/splat/segtypes/common/codesubsegment.py, src/splat/segtypes/common/data.py, src/splat/segtypes/common/rodata.py, src/splat/segtypes/ps2/ctor.py, src/splat/segtypes/ps2/lit4.py, src/splat/segtypes/ps2/lit8.py, src/splat/segtypes/ps2/vtables.py
This sections are configured to behave in a very specific way, since we know the data they contain.
* `lit4` and `lit8`: "Literal" sections that only contain `float`s and `double`s respectively.
* `ctor`: Data pointing to C++ global data initialization functions.
* `vtables`: C++ vtables
One major missing ps2/c++ section is the `init` section (the `ctor` data points to symbols from this section).
The `init` section is another executable that is autogenerated by the compiler. It contains functions to initialize global or static C++ objects.
This PR does not include that section because I'm not sure yet how the workflow of migrating this section to the `.cpp` file would work like.
I have a WIP implementation that I'm toying with here, in case anybody wants to take a look at it: …
=> Add a few ps2 segments

CHANGELOG.md, README.md, pyproject.toml, src/splat/__init__.py, src/splat/segtypes/common/code.py, src/splat/segtypes/common/pad.py, src/splat/segtypes/n64/linker_offset.py
Fixed a bug where auto segments insertion may not respect the proper ordering if there are linker_offset segments present
=> autosegments insertion fix

CHANGELOG.md, README.md, docs/Configuration.md, pyproject.toml, src/splat/__init__.py, src/splat/segtypes/common/c.py, src/splat/util/options.py, test.py
I found that `disassemble_all` was a great addition that made it pretty easy to quickly use or analyze the original assembly of an already matched function. That said, it splits the assembly for matching functions to the nonmatching path. While this isn't a big deal, I do think it is a determent to organization, and may possibly conflict with some makefiles or progress scripts which blindly scan the `nonmatching` folder.
This PR adds an option that works alongside `disassemble_all`, where if a function is a _global asm func_, and if `disassemble_all` is true, it will be split to the directory pointed to by a new variable `matchings_path`. I set the default value of this variable to `matchings`.
Besides being a solution to the problems I listed earlier, this might also have the benefit of …
=> Add `matchings_path` option to be used alongside `disassemble_all`

docs/Examples.md
Includes Legacy of Kain: Soul Reaver as an example of a PSX project that uses splat.
=> Add Legacy of Kain: Soul Reaver to the PS1 Projects list

CHANGELOG.md, README.md, docs/Segments.md, pyproject.toml, src/splat/__init__.py, src/splat/segtypes/common/textbin.py
Having the asm files to point to the src path instead of the data path makes it easier to commit them to the repo.
I also wrote some docs for incbins given that I noted we had none
=> Option to make incbins relative to the src path instead of data path

CHANGELOG.md, README.md, docs/Configuration.md, pyproject.toml, src/splat/__init__.py, src/splat/segtypes/common/c.py, src/splat/segtypes/common/code.py, src/splat/util/__init__.py, src/splat/util/utils.py
- Fix pairing text to other sections on cases where text is not be the first section.
- Fix some code that assumes that `.rodata` will always be present on the `sections_order` list.
- Fix `.text`/`.rdata` section pairing (hopefully).
- Emit an error if we try to migrate the rodata symbols to functions if the rodata section is not prefixed with a dot (ie `- [0x1234, rodata, some_file]` instead of `- [0x1234, .rodata, some_file]`)
- Not prefixing the type with a dot would produce splat to both disassemble the rodata section to its own assembly file and to migrate the symbols to the corresponding functions, generating link-time errors and many headaches.
- Rewrite the `ld_legacy_generation` docs for clarity.
=> Fix some `rdata` issues

CHANGELOG.md, src/splat/scripts/split.py, src/splat/segtypes/common/code.py, src/splat/segtypes/common/group.py, src/splat/segtypes/n64/img.py, src/splat/segtypes/segment.py
* Fixed not being able to disable the `subalign` directive for a given segment.
* Removed bugged alignment check on image segments.
* splat will now error out if any of the following attributes is specified in a non top-level segment.
* `subalign`
* `ld_fill_value`.
=> Fix not being able to disable `SUBALIGN` on the segment level and remove bugged image alignment check

CHANGELOG.md, README.md, docs/Adding-Symbols.md, docs/Configuration.md, pyproject.toml, requirements.txt, src/splat/__init__.py, src/splat/disassembler/spimdisasm_disassembler.py, src/splat/util/symbols.py
Brief explanation of the new symbol attributes:
* `function_owner`: Allows to force a rodata symbol to be migrated to the given function, skipping over the rodata migration heuristic.
* `allow_reference`: Allows toggling if the symbol is allowed to reference other symbols.
* `allow_be_referenced`: Allows toggling if the symbol is allowed to be referenced by other symbols.
Rewrite docs for `o_as_suffix`. Hopefully it is more clear this way.
`spimdisasm` 1.29.0 or above is now required.
=> Add new symbol attributes (`function_owner`, `allow_reference`, `allow_be_referenced`)

CHANGELOG.md, README.md, pyproject.toml, src/splat/__init__.py, src/splat/util/symbols.py
spimdisasm crashes on an `assert` if you try to pass it a zero sized overlay, since it would throw off its per-segment analysis.
So this fixes this issue on splat's side because of the linker script generator.
=> Fix crash on zero-sized segments

CHANGELOG.md, README.md, pyproject.toml, src/splat/__init__.py, src/splat/scripts/split.py, src/splat/segtypes/common/code.py, src/splat/segtypes/common/group.py, src/splat/segtypes/segment.py
=> Fix bss/sbss asm files not being generated

CHANGELOG.md, README.md, pyproject.toml, src/splat/__init__.py, src/splat/scripts/create_config.py
=> `create_config` fix: Avoid creating files with invalid path names

CHANGELOG.md, README.md, pyproject.toml, src/splat/__init__.py, src/splat/util/compiler.py
Fixes incorrect detection of non existing functions
=> Tag `PSYQ` as a compiler that uses `j` instructions as branches

CHANGELOG.md, pyproject.toml, src/splat/scripts/split.py, src/splat/segtypes/common/bin.py, src/splat/segtypes/common/group.py, src/splat/segtypes/common/segment.py, src/splat/segtypes/segment.py, src/splat/util/statistics.py
Fixes #432 
Extend `util.Statistics` so that it breaks out statistics for segments which include subsegments.
I extended the base `Segment` type to include a property `statistics` for querying subsegment statistics, defaulting to the current segment information only. `CommonSegGroup` overrides this to provide aggregated statistics based on all of its subsegments.
This change has the effect that a segment inheriting from `CommonSegGroup` will not be itself included in the statistics output. An example is given in the test output below.
I'm not sure if this is desired behavior, but I couldn't figure out a way to incorporate both subsegment information and retain the segment name without changing the output into some kind of tree format. 
Using the following segment configuration:
```yaml …
```
=> Include subsegment information when aggregating split statistics

CHANGELOG.md, README.md, pyproject.toml, requirements.txt, src/splat/__init__.py, src/splat/disassembler/spimdisasm_disassembler.py, src/splat/segtypes/common/codesubsegment.py, src/splat/segtypes/common/data.py, src/splat/segtypes/common/rodata.py
This hopefully should fix some jumptable labels not using the proper naming format specified by the user
=> Fix jtbl labels missing segment suffixes

CHANGELOG.md, README.md, pyproject.toml, src/splat/__init__.py, src/splat/segtypes/common/bss.py, src/splat/segtypes/common/code.py, src/splat/segtypes/common/group.py, src/splat/segtypes/segment.py
Slightly speed up `bss` disassembly for projects over thousands of subsegments in the same top-level segment. Projects with saner amount of subsegments won't see a difference after this. I think this will be useful for PS2 projects
Measuring how much it takes to disassemble the hit and run project, which has over 3k subsegments:
- Before this PR
```
real    0m43.467s
user    0m42.275s
sys    0m0.925s
```
- After this PR
```
real    0m41.629s
user    0m40.556s
sys    0m0.983s
```
=> Slightly faster bss disassembly for huge segments

src/splat/scripts/split.py, src/splat/util/conf.py, src/splat/util/options.py, test.py
Moves splat config loading and parsing into `splat.util.conf` to make it available to other projects.
`initialize_config` is now `splat.util.conf.load`. It takes `Path`s instead of `str`s for YAML paths. It will no longer `exit` if config merging fails, but will throw a `TypeError` which can be handled as desired by callers.
=> Separate Config from Split

src/splat/segtypes/common/c.py, src/splat/segtypes/common/textbin.py
The generation of these macros uses a path class which outputs slashes relative to the OS. This creates an issue when splat is run on windows, as it will generate:
`INCLUDE_ASM("asm\nonmatchings\game", func_800AF980);`
The preprocessor will then treat these as escape sequences and do wild things. This fix forces it to always use unix paths regardless of OS:
`INCLUDE_ASM("asm/nonmatchings/game", func_800AF980);`
=> Fix include macros when generated on windows

src/splat/segtypes/common/textbin.py, src/splat/util/compiler.py
ASN64 requires labels to be used for globals in order to access them, which by default, are not generated for text/(ro)databins. It is however generated for regular code, as [shown here](https://github.com/ethteck/splat/blob/main/src/splat/disassembler/spimdisasm_disassembler.py#L105). I simply mimicked the same logic for the incbin generation. With this fix, an SN64 rom can now be split and reassembled to bin exactness without any manual changes done to splat's output, via `modern-asn64`.
Before:
```
.globl gspF3DEX2_fifoTextStart
.incbin "assets/rsp/gspF3DEX2_fifo.textbin.bin"
.end gspF3DEX2_fifoTextStart
```
After:
```
.globl gspF3DEX2_fifoTextStart
.ent gspF3DEX2_fifoTextStart
gspF3DEX2_fifoTextStart:
.incbin "assets/rsp/gspF3DEX2_fifo.textbin.bin"
.end gspF3DEX2_fifoTextStart
```
=> Fix output of incbins for SN64

docs/Configuration.md
Add entries for `ld_sections_allowlist` and `ld_sections_denylist` to the Configuration section of the wiki.
I also checked every other setting and seems like this two were the only ones that were missing an entry on the wiki.
=> Document missing settings on `Configuration.md`

src/splat/segtypes/common/hasm.py
Tested with Yoshi's story.
Before: hasm files would get overwritten.
After: hasm files persist if they already exist
=> Don't split hasm file if path already exists

CHANGELOG.md, README.md, pyproject.toml, src/splat/__init__.py, src/splat/segtypes/segment.py, test.py
Also checks if a bss section is somehow outside it's parent segment's address space, which may be caused by a `bss_size` value being too small.
These checks aren't performed if `ld_bss_is_noload` is disabled, like for psx projects.
=> Emit an error if `bss_size` is missing on segments that do contain `bss` sections

CHANGELOG.md, README.md, pyproject.toml, src/splat/__init__.py, src/splat/util/file_presets.py
We missed a dot in the include directive in the generated `macro.inc` file.
This only affects psx projects.
Fixes #470
=> Fix missing dot at `.include` in generated `macro.inc` file

CHANGELOG.md, README.md, pyproject.toml, src/splat/__init__.py, src/splat/util/file_presets.py
splat was ignoring when you turn off the `generate_asm_macros_files` option. My bad.
Fixes #472
=> Fix `generate_asm_macros_files` option

src/splat/util/file_presets.py
Documentation [here](https://problemkaputt.de/psx-spx.htm#gteoverview).
Needs more testing as Vagrant Story only uses a handful of the ops, and it looks like there might have been a bug in DPCT which this fixes.
=> Refactor GTE macros to better document opcode encoding
